version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.no-redis
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - API_KEY=${API_KEY}
      - PORT=${PORT:-8000}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3