version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - REDIS_HOST=redis://redis:6379/0
      - API_KEY=${API_KEY:-your-secret-api-key-here}
      - PORT=${PORT:-8000}
      - HOST=0.0.0.0
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    command: celery -A worker.tasks worker --loglevel=info

volumes:
  redis_data: